name: shadcn_ui
description: shadcn/ui ported in Flutter. Awesome UI components for Flutter, fully customizable.
version: 0.28.4
homepage: https://flutter-shadcn-ui.mariuti.com
repository: https://github.com/nank1ro/flutter-shadcn-ui
documentation: https://flutter-shadcn-ui.mariuti.com
topics:
  - user-interface
  - design-system
  - shadcn-ui
  - material-alternative

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  boxy: ">=2.0.0 <3.0.0"
  collection: ">=1.0.0 <2.0.0"
  flutter:
    sdk: flutter
  flutter_animate: ">=4.1.0 <5.0.0"
  flutter_localizations:
    sdk: flutter
  flutter_svg: ">=2.0.0 <3.0.0"
  intl: ">=0.19.0 <1.0.0"
  lucide_icons_flutter: ">=3.0.0 <4.0.0"
  # used by Table
  two_dimensional_scrollables: ">=0.2.0 <1.0.0"
  universal_image: ">=1.0.3 <2.0.0"
  vector_graphics: ">=1.0.0 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

